### PR TITLE
set sidebar details summary text to gray

### PR DESCRIPTION
**Pull request by tbeseda**
sidebar

Chrome accessibility inspector gives this a decent contrast score of 6.38

I considered changing the icon, too but [styling a `<summary>`'s marker shape thing is a PITA apparently](https://css-tricks.com/quick-reminder-that-details-summary-is-the-easiest-way-ever-to-make-an-accordion/)

### CODE REVIEW

**Comment by macdonst** [comment]
The color contrast is fine in dark mode but in light mode axe-core reports an issue. Here is an alternative idea, we make the color match the rest of the side nav links and hide the summary arrow.

sidenav

This can be accomplished by changing the the class on the summary element to `text-p1` at line 105 of sidebar.js and adding the following CSS to index.css:

```css

details > summary {
  list-style: none;
}
details > summary::-webkit-details-marker {
  display: none;
}
```

That should hide the element for all browsers or at least Chrome, FF and Safari which I was able to quickly test.

I'm still thinking we should have some sort of visual indicator to let the reader know this is a menu item that can be expanded. We could accomplish that but adding a SVG to the summary but let's run the options by Ryan as he's the initial reporter.

**Comment by macdonst** [comment]
What do you think about this @tbeseda?

expand-menu

**Comment by tbeseda** [comment]
Nice! Definitely a good solve
A couple ideas: could the icon have no fill? just an outline circle around the symbol? And is it vertically centered in in the line height? looks like it might be top aligned, hard to tell.

**Comment by macdonst** [comment]
@tbeseda this is as good as I can do

expand-menu

**Comment by tbeseda** [comment]
I vote for option 2, but let's see if we can get others to weigh in :) -- maybe @kristoferjoseph ?

**Comment by macdonst** [comment]
Yeah, the latest commit looks best to me.

**Pull request merged**
