### PR TITLE
Added tutorial for setting up custom domains

### PR DESCRIPTION
**Pull request by ShawnHosea**
Added tutorials for setting up custom domains.

- Route53
- Godaddy
- Namecheap
- One.com
- Dreamhost
- Cloudflare

### CODE REVIEW

**Comment by ryanblock** [comment]
Hey, sorry to come in late on this, but I cannot in good conscience promote the use of CloudFlare, or any other service that aids and abets white supremacists.

**Comment by filmaj** [comment]
I think we need to remove all references to Begin.

**Comment by ryanblock** [comment]
If there are any, then yes, def.

**Comment by ShawnHosea** [comment]
Thanks for the sweep @filmaj @ryanblock. I removed the links to Cloudflare and removed all references to Begin.

**Pull request merged**
