### PR TITLE
Plugin Docs

### PR DESCRIPTION
**Pull request by filmaj**
This is related to architect/architect#1062.

This PR covers the plugin author-facing documentation. The interfaces a plugin author must implement, along with examples where relevant.

Currently this is a draft PR - I would not merge until all the other supporting pieces in all other architect modules pass review and are merged.

### CODE REVIEW

**Comment by Ankcorn** [comment]
Hey, look great!

Over the next few days, I will try to use this to create a basic plugin (aware it won't work but will be a fun exercise)

I was thinking a plugin to create extra s3 buckets and run them locally would be cool.

**Comment by filmaj** [comment]
That would be super awesome! Appreciate any feedback at all, re: names, or what feels awkward, etc. I wanted to focus on the plugin-author-facing stuff first and have feedback there inform the implementation of it all rather than the other way around.

**Comment by Ankcorn** [comment]
It took me a moment to spot in your example code that I could do 

```javascript
inventory.inv._project.arc
```

would it be possible to pass them the arc config object too like the package function? :)

**Comment by filmaj** [comment]
@Ankcorn totally! In terms of implementation it is trivial since `@architect/inventory` provides that for free. Perhaps worth just adding that as a convenience parameter across all of the plugin interface functions, then?

**Comment by Ankcorn** [comment]
Once I found it in inventory it was not so bad. It would not deter me from creating a plugin. 

Does _project imply that I am accessing a private property though? I am aware that is a convention for some projects. 
I would prefer my hypothetical plugin not to depend on private properties if possible to avoid any breaking changes

🥰

**Comment by filmaj** [comment]
> Does _project imply that I am accessing a private property though? I am aware that is a convention for some projects.
I would prefer my hypothetical plugin not to depend on private properties if possible to avoid any breaking changes

Yeah makes sense. I think making the argument list consistent (by putting the parsed `arc` object as the first argument) makes for nice symmetry anyways.

As for your bucket plugin implementation, the `start` method looks a little off. Based on how I have that interface drafted up, the `start` and `end` sandbox methods should return a function that accepts a callback and which fires the callback once the sandbox plugin service is ready. So it should look something like:

```
start: async function (inventory) {
  const arc = inventory.inv._project.arc
  s3Instance = new S3rver({ configureBuckets: arc.buckets.map(b=> `${b}-testing`), ...defaultLocalOptions})
  return function(callback) {
    await s3Instance.run()
    callback()
  }
}
```

.. but looking at the above, the whole "return a function with a callback" return response is a bit awkward. I only decided on that as what [arc sandbox will do under the hood is collect all plugins and, in series, run each plugins' `start` method](https://github.com/copperinc/sandbox/blob/plugins/src/sandbox/start.js#L88-L112).

However, I could probably `bind` the plugin `start` methods with the appropriate arguments so that the plugin author doesn't need to return a function. Instead, a callback would be passed as a last argument that the plugin author would have to invoke. So, using your plugin as the example base, perhaps something like this is better (and also adding the new first `arc` argument in here while I'm at it):

```
start: async function (arc, inventory, callback) {
  s3Instance = new S3rver({ configureBuckets: arc.buckets.map(b=> `${b}-testing`), ...defaultLocalOptions})
  await s3Instance.run()
  callback()
}
```

(probably need to check that `arc.buckets` exists in the above but you hopefully get the idea)

**Comment by Ankcorn** [comment]
> As for your bucket plugin implementation, the start method looks a little off.

Ah I totally blanked on that!

Using a callback works in the s3 case as you can do this


```javascript
start: function (arc, inventory, callback) {
  s3Instance = new S3rver({ configureBuckets: arc.buckets.map(b=> `${b}-testing`), ...defaultLocalOptions}).run(callback)
}
```

mixing callbacks and async is a bit weird though right? I don't understand any of the arc internals though so don't want to throw up any blockers related to that stuff

**Comment by Ankcorn** [comment]
So I had a dabble and you could maybe achieve the run-series in the sandbox with a mix of promise and callbacks like this

```javascript
const util = require('util');

function start(callback) {
	callback(null,'hi')
}

async function start1() {
	return 'hi'
}

async function runSeries(functions) {
	for(let func of functions) {
		const isAsync = func.constructor.name === "AsyncFunction";
		let unresolvedPromise = isAsync ? func() : util.promisify(func)();
		const result = await unresolvedPromise;
		console.log(result)
	}
}


runBoth([start,start1]);
```

**Comment by filmaj** [comment]
Love it! Great idea. I'll jump back in on this PR soon to update it based on our conversations.

**Comment by filmaj** [comment]
Alright took your feedback and integrated back into the docs. I think it's looking better!

**Comment by Ankcorn** [comment]
Thanks!

Looking at adding S3 Events support to the plugin tonight. Let's see if I can implement the pluginFunctions correctly! :)

**Comment by brianleroux** [comment]
(just wanted to say liking where this is going @filmaj !)

**Comment by filmaj** [comment]
I am merging this in so that the docs are live up on staging.arc.codes; will be cutting an RC of architect shortly so we can give this a spin!

**Pull request merged**
