### PR TITLE
fixing broken links

### PR DESCRIPTION
**Pull request by jessehattabaugh**

### CODE REVIEW

**Comment by brianleroux** [comment]
thx jesse!! 

think we need to tag to release…we just moved to ghactions (is that right @ryanblock ?)

**Comment by ryanblock** [comment]
That's correct, tag to release.

**Comment by brianleroux** [comment]
@ryanblock heads up but looks like it only goes to staging rn https://github.com/architect/arc.codes/runs/321944270

**Comment by ryanblock** [comment]
Hmm, my config may be behind here. I'll make sure this gets to production this afternoon!

**Comment by ryanblock** [comment]
Ok, should all be deployed, thanks again @jessehattabaugh!

**Pull request merged**
