### PR TITLE
remove hljs in favor of shiki

### PR DESCRIPTION
**Pull request by tbeseda**
Related to #366 

For now I just copied [the tmGrammar](https://github.com/ryanblock/architect-vscode-grammar-extension/blob/master/syntaxes/arc.tmGrammar.json) from @ryanblock's VS Code extension. In the future the grammar can be extracted away from this package so that it can also be used elsewhere

### Notes
* the `getHighlighter` method is async because it uses WASM under the hood to highlight
* the `langs` property is optional, but specifying used languages speeds up the highlighter 🍕 
* code-fencing with \```js works fine, but I changed all instances to \```javascript for consistency
* changed `typography` to `typographer` in the markdown-it `Markdown` instance
* this also helped clean up some typing issues around Markdown and the highlighter

---

<details open>
<summary>PR Template</summary>
### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [x] Forked the repo and created your branch from `master`
- [x] Made sure tests pass (run `npm it` from the repo root)
- [x] Updated relevant documentation internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
- [x] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA as it's required for your PR to be merged. A github comment will prompt you if you haven't already.

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!
</details>

### CODE REVIEW

**Comment by tbeseda** [comment]
@kristoferjoseph FYI I removed the hljs related CSS since shiki provides styles inline according to the theme you pass it.

I chose the `dracula-soft` theme since it seemed most similarly matched the previous hljs theme, however let me know if you like one of [the available themes in Shiki](https://github.com/shikijs/shiki/blob/main/docs/themes.md#all-themes) better. or we can even add our own to the repo.

shiki-arc-codes

**Comment by kristoferjoseph** [comment]
I am not a fan of the dracula-soft theme.
The entire website color scheme is based off of the code color scheme. 
Is there a way to port the existing code color scheme to shiki?

**Comment by tbeseda** [comment]
> [Hemisu dark](https://noahfrederick.com/vim-color-scheme-hemisu/)
> Is there a way to port the existing code color scheme to shiki?

Yep they use the VS Code standard for themes. so I can port it pretty easily.

**Comment by tbeseda** [comment]
Turns out no one has ported Hemisu to a VS Code/Textmate theme but I got it pretty close using Shiki's `css-variables` theme that let me set some broad stroke colors.

image

In order to get more specific with highlighting, we'd need a full .json theme file. Which I might go ahead and do in my free time, because I really like this theme 💅🏻 

Additionally, improving the .arc grammar specification would help Shiki with app.arc files, but it's definitely on par with what we had with hljs already.

**Comment by kristoferjoseph** [comment]
Damn @tbeseda this is really nice. Thanks for looking into that. 
I originally thought I would endeavor to make both the light and dark version of the Hemisu theme so we could have our own take on light/dark themeing of arc.codes. 
What you did here gets us much closer to realizing this dream if we ever want to in the future. 
My hope is that we could have an Architect theme for end users ( if they want to get down with lots of greens like @brianleroux  )

**Comment by tbeseda** [comment]
thx @kristoferjoseph 
I used several tools while I was toying with the theme in case you're curious:
A [Coolors.co palette](https://coolors.co/999999-444444-9fd3e6-b1d631-ece1c8-bbffaa-d65e76-005f87-5f5f00-63001c) helped with quick copy/paste of HEX as I experimented with colors in [Theme Studio](https://themes.vscode.one/user/tbeseda)* (👈🏻 that's my Studio profile where there are a few Hemisu variants) and then [the source of Hemisu](https://github.com/noahfrederick/vim-hemisu/blob/master/colors/hemisu.vim) has some color variants for each green, blue, pink etc to play with

\* I only worried about the last tab of colors in Theme Studio since those are what affect the syntax

**Pull request merged**
